/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PGZ0sLjzZCJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { CardContent, CardFooter, Card } from "@/components/ui/card"

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-gray-900 text-white py-4 px-6 md:px-10">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <Link className="text-2xl font-bold" href="#">
            Coworking Space
          </Link>
          <nav className="hidden md:flex items-center space-x-6">
            <Link className="hover:text-gray-400" href="#">
              Find Spaces
            </Link>
            <Link className="hover:text-gray-400" href="#">
              List Your Space
            </Link>
            <Link className="hover:text-gray-400" href="#">
              About
            </Link>
            <Link className="hover:text-gray-400" href="#">
              Contact
            </Link>
          </nav>
          <Button className="md:hidden" size="sm" variant="outline">
            Menu
          </Button>
        </div>
      </header>
      <section className="bg-gray-900 text-white py-20 px-6 md:px-10">
        <div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-8 items-center">
          <div>
            <h1 className="text-4xl font-bold mb-4">Find the Perfect Coworking Space</h1>
            <p className="text-lg mb-8">Discover and book the best coworking spaces for your business.</p>
            <form className="flex items-center bg-white rounded-md overflow-hidden">
              <Input
                className="flex-1 px-4 py-3 text-gray-700 focus:outline-none"
                placeholder="Search by location or amenities"
                type="text"
              />
              <Button className="bg-gray-900 text-white px-6 py-3" type="submit">
                Search
              </Button>
            </form>
          </div>
          <div className="hidden md:block">
            <img
              alt="Coworking Space"
              className="rounded-lg"
              height={400}
              src="/placeholder.svg"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width={600}
            />
          </div>
        </div>
      </section>
      <section className="bg-gray-100 py-12 px-6 md:px-10">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold mb-8">Available Coworking Spaces</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
            <Card>
              <img
                alt="Coworking Space"
                className="rounded-t-lg object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400}
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-bold mb-2">Acme Coworking</h3>
                <p className="text-gray-600 mb-2">123 Main St, Anytown USA</p>
                <div className="flex items-center justify-between">
                  <p className="text-gray-700 font-bold">$99/month</p>
                  <Badge variant="success">Available</Badge>
                </div>
              </CardContent>
              <CardFooter className="p-4">
                <Button size="sm">View Details</Button>
              </CardFooter>
            </Card>
            <Card>
              <img
                alt="Coworking Space"
                className="rounded-t-lg object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400}
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-bold mb-2">Cowork Central</h3>
                <p className="text-gray-600 mb-2">456 Oak Rd, Somewhere City</p>
                <div className="flex items-center justify-between">
                  <p className="text-gray-700 font-bold">$149/month</p>
                  <Badge variant="warning">Limited Availability</Badge>
                </div>
              </CardContent>
              <CardFooter className="p-4">
                <Button size="sm">View Details</Button>
              </CardFooter>
            </Card>
            <Card>
              <img
                alt="Coworking Space"
                className="rounded-t-lg object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400}
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-bold mb-2">Workspace Hub</h3>
                <p className="text-gray-600 mb-2">789 Elm St, Somewhere Else</p>
                <div className="flex items-center justify-between">
                  <p className="text-gray-700 font-bold">$79/month</p>
                  <Badge variant="danger">Fully Booked</Badge>
                </div>
              </CardContent>
              <CardFooter className="p-4">
                <Button size="sm">View Details</Button>
              </CardFooter>
            </Card>
            <Card>
              <img
                alt="Coworking Space"
                className="rounded-t-lg object-cover"
                height={300}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/300",
                  objectFit: "cover",
                }}
                width={400}
              />
              <CardContent className="p-4">
                <h3 className="text-xl font-bold mb-2">Collab Hub</h3>
                <p className="text-gray-600 mb-2">321 Pine St, Another Town</p>
                <div className="flex items-center justify-between">
                  <p className="text-gray-700 font-bold">$129/month</p>
                  <Badge variant="success">Available</Badge>
                </div>
              </CardContent>
              <CardFooter className="p-4">
                <Button size="sm">View Details</Button>
              </CardFooter>
            </Card>
          </div>
        </div>
      </section>
    </div>
  )
}
